version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ai-news-ollama
    ports:
      - "11434:11434"
    volumes:
      - ai_news_ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - ai-news-network

  ai-news-api:
    build: .
    container_name: ai-news-api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434/v1
      - OLLAMA_MODEL=qwen3:0.6b-q4_K_M
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - ai-news-network

volumes:
  ai_news_ollama_data:
    driver: local

networks:
  ai-news-network:
    driver: bridge
